# Generated by Django 5.1.7 on 2025-03-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='avaliação',
            new_name='avaliacao',
        ),
    ]
